// Generated by scripts/build-plugin.mjs from src/core/conflict.js and status.js. Do not edit.
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  try {
    return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
  } catch (e) {
    throw mod = 0, e;
  }
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// src/core/status.js
var require_status = __commonJS({
  "src/core/status.js"(exports, module) {
    (function(root, factory) {
      const api = factory();
      if (typeof module !== "undefined" && module.exports) module.exports = api;
      if (typeof window !== "undefined") window.PortPilotStatus = api;
    })(typeof self !== "undefined" ? self : exports, function() {
      "use strict";
      const STATES = {
        running: { state: "running", token: "--status-running", shape: "disc", glyph: "\u25CF", ascii: "*", label: "Running" },
        stopped: { state: "stopped", token: "--status-stopped", shape: "ring", glyph: "\u25CB", ascii: "o", label: "Stopped" },
        starting: { state: "starting", token: "--status-starting", shape: "disc-pulse", glyph: "\u25D0", ascii: "~", label: "Starting" },
        conflict: { state: "conflict", token: "--status-conflict", shape: "triangle", glyph: "\u25B2", ascii: "!", label: "Conflict" },
        error: { state: "error", token: "--status-error", shape: "circle-x", glyph: "\u2297", ascii: "x", label: "Error" },
        crashed: { state: "crashed", token: "--status-crashed", shape: "cross", glyph: "\u2715", ascii: "X", label: "Crashed" }
      };
      function statusOf2(item) {
        const it = item || {};
        if (it.state && STATES[it.state]) return STATES[it.state];
        if (it.crashed) return STATES.crashed;
        if (it.error) return STATES.error;
        if (it.conflict) return STATES.conflict;
        if (it.starting) return STATES.starting;
        if (it.running) return STATES.running;
        return STATES.stopped;
      }
      const GROUPS = {
        dev: { key: "dev", label: "Dev Servers", order: 0, defaultCollapsed: false },
        other: { key: "other", label: "Other User Ports", order: 1, defaultCollapsed: false },
        system: { key: "system", label: "System & OS Ports", order: 2, defaultCollapsed: true }
      };
      const GROUP_ORDER = ["dev", "other", "system"];
      const SYSTEM_PROCESSES = /* @__PURE__ */ new Set([
        // Windows
        "system",
        "system idle process",
        "idle",
        "registry",
        "svchost.exe",
        "services.exe",
        "lsass.exe",
        "wininit.exe",
        "winlogon.exe",
        "smss.exe",
        "csrss.exe",
        "spoolsv.exe",
        "searchindexer.exe",
        "searchhost.exe",
        "dwm.exe",
        "taskhostw.exe",
        "vmms.exe",
        "vmwp.exe",
        "vmcompute.exe",
        "wslservice.exe",
        "msmpeng.exe",
        // macOS / Linux
        "launchd",
        "systemd",
        "systemd-resolve",
        "systemd-resolved",
        "rpcbind",
        "rpc.statd",
        "rpc.mountd",
        "mdnsresponder",
        "cupsd",
        "avahi-daemon",
        "dnsmasq",
        "smbd",
        "nmbd"
      ]);
      const SYSTEM_PORTS = /* @__PURE__ */ new Set([
        135,
        // MS RPC endpoint mapper
        137,
        138,
        139,
        // NetBIOS
        445,
        // SMB
        1900,
        // SSDP / UPnP
        2179,
        // Hyper-V VMConnect (vmms.exe)
        3702,
        // WS-Discovery
        5353,
        // mDNS / Bonjour
        5355,
        // LLMNR
        5357,
        // WSDAPI
        631
        // CUPS / IPP
      ]);
      const DEV_RUNTIME_TOKENS = [
        "node",
        "nodejs",
        "deno",
        "bun",
        "npm",
        "npx",
        "pnpm",
        "yarn",
        "nodemon",
        "vite",
        "next",
        "nuxt",
        "astro",
        "remix",
        "webpack",
        "rollup",
        "esbuild",
        "parcel",
        "turbo",
        "ng",
        "ember",
        "gatsby",
        "expo",
        "python",
        "python3",
        "uvicorn",
        "gunicorn",
        "hypercorn",
        "flask",
        "django",
        "fastapi",
        "streamlit",
        "php",
        "artisan",
        "ruby",
        "rails",
        "puma",
        "unicorn",
        "dotnet",
        "cargo",
        "hugo",
        "air"
      ];
      const DEV_RUNTIME_RE = new RegExp("\\b(" + DEV_RUNTIME_TOKENS.join("|") + ")\\b");
      const DEV_RANGE_MIN = 3e3;
      const DEV_RANGE_MAX = 9999;
      function classify(port, opts) {
        const p = port || {};
        const o = opts || {};
        const num = Number(p.port);
        const pid = p.pid;
        const proc = String(p.processName || "").toLowerCase().trim();
        const text = (proc + " " + String(p.commandLine || "")).toLowerCase();
        if (o.registered === true || p.appId != null || p.registered === true) return "dev";
        if (pid === 0 || pid === 4) return "system";
        if (SYSTEM_PROCESSES.has(proc)) return "system";
        if (SYSTEM_PORTS.has(num)) return "system";
        if (DEV_RUNTIME_RE.test(text) && num >= DEV_RANGE_MIN && num <= DEV_RANGE_MAX) return "dev";
        return "other";
      }
      const PROVENANCE_KINDS = ["human", "claude", "external"];
      const SURFACES = ["desktop", "web", "vscode", "claude-code", "mcp"];
      const CLAUDE_GLYPH2 = "\u2726";
      function makeStartedBy(fields) {
        const f = fields || {};
        if (!PROVENANCE_KINDS.includes(f.kind)) {
          throw new Error("startedBy.kind must be one of: " + PROVENANCE_KINDS.join(", "));
        }
        if (!SURFACES.includes(f.surface)) {
          throw new Error("startedBy.surface must be one of: " + SURFACES.join(", "));
        }
        const out = { kind: f.kind, surface: f.surface, at: f.at || (/* @__PURE__ */ new Date()).toISOString() };
        if (f.sessionId) out.sessionId = String(f.sessionId).slice(0, 200);
        if (f.label) out.label = String(f.label).slice(0, 100);
        return out;
      }
      function shortSession(id) {
        return id ? String(id).replace(/[^A-Za-z0-9]/g, "").slice(0, 4).toLowerCase() : "";
      }
      function provenanceOf2(startedBy) {
        const s = startedBy || null;
        if (!s || s.kind === "external" || !PROVENANCE_KINDS.includes(s.kind)) {
          return { kind: "external", word: "external", glyph: "", title: "Found running - not started by PortPilot" };
        }
        const when = s.at ? ` at ${s.at}` : "";
        if (s.kind === "human") {
          return { kind: "human", word: "you", glyph: "", title: `Started by you from ${s.surface}${when}` };
        }
        const short = shortSession(s.sessionId);
        const session = s.sessionId ? ` (session ${s.sessionId}${s.label ? `, ${s.label}` : ""})` : "";
        return {
          kind: "claude",
          word: short ? `claude ${short}` : "claude",
          glyph: CLAUDE_GLYPH2,
          title: `Started by Claude${session} via ${s.surface}${when}`
        };
      }
      return {
        STATES,
        statusOf: statusOf2,
        PROVENANCE_KINDS,
        SURFACES,
        CLAUDE_GLYPH: CLAUDE_GLYPH2,
        makeStartedBy,
        shortSession,
        provenanceOf: provenanceOf2,
        GROUPS,
        GROUP_ORDER,
        classify,
        // Exposed for tests and future tuning.
        SYSTEM_PROCESSES,
        SYSTEM_PORTS,
        DEV_RUNTIME_RE,
        DEV_RANGE_MIN,
        DEV_RANGE_MAX
      };
    });
  }
});

// src/core/conflict.js
var require_conflict = __commonJS({
  "src/core/conflict.js"(exports, module) {
    (function(root, factory) {
      const api = factory(root);
      if (typeof module !== "undefined" && module.exports) module.exports = api;
      if (typeof window !== "undefined") window.PortPilotConflict = api;
    })(typeof self !== "undefined" ? self : exports, function(root) {
      "use strict";
      const CONFIRM_MS2 = 3e3;
      function statusApi() {
        if (typeof module !== "undefined" && module.exports) return require_status();
        return root && root.PortPilotStatus;
      }
      function fmtAge2(seconds) {
        const s = Number(seconds);
        if (!Number.isFinite(s) || s < 0) return "";
        if (s < 60) return "just now";
        if (s < 3600) return `${Math.floor(s / 60)}m ago`;
        if (s < 86400) return `${Math.floor(s / 3600)}h ago`;
        return `${Math.floor(s / 86400)}d ago`;
      }
      function describeConflict2(c) {
        const o = c || {};
        const port = Number(o.port);
        const holder = o.holder || {};
        const holderApp = o.holderApp && o.holderApp.name ? o.holderApp : null;
        const kind = holderApp ? "managed" : "unmanaged";
        const proc = holder.processName || "an unknown process";
        const holderName = holderApp ? holderApp.name : proc;
        const S = statusApi();
        const prov = o.holderStartedBy && S ? S.provenanceOf(o.holderStartedBy) : null;
        const known = prov && prov.kind !== "external";
        const details = [];
        if (holderApp) details.push(proc);
        if (holder.pid != null) details.push(`PID ${holder.pid}`);
        const age = fmtAge2(holder.uptime);
        if (age) details.push(`started ${age}`);
        if (known) details.push(`started by ${prov.word}`);
        else if (!holderApp) details.push("not managed");
        const sentence = `:${port} is held by ${holderName}` + (details.length ? ` (${details.join(", ")})` : "");
        const title = known ? prov.title : "";
        const freePort = Number(o.freePort) || null;
        const appName = o.app && o.app.name ? o.app.name : "the app";
        const actions = [
          {
            id: "useFreePort",
            label: freePort ? `Use :${freePort} instead` : "Use next free port",
            title: `Start ${appName} on ${freePort ? `:${freePort}` : "the next free port"} for this run. The saved port stays :${port}.`,
            destructive: false,
            recommended: true
          },
          {
            id: "killAndStart",
            label: holderApp ? `Stop ${holderApp.name} & start` : "Kill & start",
            title: `End ${holderName}${holder.pid != null ? ` (PID ${holder.pid})` : ""}, then start ${appName} on :${port}`,
            confirmLabel: holderApp ? "Confirm stop?" : "Confirm kill?",
            destructive: true,
            recommended: false
          },
          {
            id: "showProcess",
            label: "Show process",
            title: `Find :${port} in the Ports list`,
            destructive: false,
            recommended: false
          }
        ];
        return { kind, port, holderName, sentence, title, actions };
      }
      return { CONFIRM_MS: CONFIRM_MS2, fmtAge: fmtAge2, describeConflict: describeConflict2 };
    });
  }
});

// src/core/plugin-core-entry.js
var import_conflict = __toESM(require_conflict());
var import_status = __toESM(require_status());
var export_CLAUDE_GLYPH = import_status.CLAUDE_GLYPH;
var export_CONFIRM_MS = import_conflict.CONFIRM_MS;
var export_describeConflict = import_conflict.describeConflict;
var export_fmtAge = import_conflict.fmtAge;
var export_provenanceOf = import_status.provenanceOf;
var export_statusOf = import_status.statusOf;
export {
  export_CLAUDE_GLYPH as CLAUDE_GLYPH,
  export_CONFIRM_MS as CONFIRM_MS,
  export_describeConflict as describeConflict,
  export_fmtAge as fmtAge,
  export_provenanceOf as provenanceOf,
  export_statusOf as statusOf
};
