#!/usr/bin/env node
// Builds the code that ships inside the Claude Code plugin.
//
// A plugin installed from git gets no `npm install`, so mcp-server/index.js is
// bundled with its one dependency (@modelcontextprotocol/sdk) into a single ESM
// file. The two core helpers it loads at runtime (configFile, status) are copied
// next to it as .cjs, the same layout electron-builder ships (see "build" in
// package.json), so loadCore() finds them without any source change.
//
// It also bundles the core modules the hooks mod imports (conflict, and status
// behind it) into plugin/hooks/lib/core.mjs: the mod runs as an ES module with
// no require, so the UMD sources cannot be imported as they are.
//
//   node scripts/build-plugin.mjs           write plugin/mcp/ and plugin/hooks/lib/
//   node scripts/build-plugin.mjs --check   exit 1 if either is stale
//
// The output is committed. tests/plugin-bundle.test.cjs runs --check.

import { build } from 'esbuild';
import fs from 'fs';
import os from 'os';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pluginDir = path.join(root, 'plugin');
// Generated folders under plugin/, compared file by file by --check.
const OUTPUTS = ['mcp', 'hooks/lib'];
const check = process.argv.includes('--check');

async function buildTo(base) {
  const mcpDir = path.join(base, 'mcp');
  fs.mkdirSync(mcpDir, { recursive: true });
  await build({
    absWorkingDir: root, // path comments in the bundle must not depend on cwd
    entryPoints: [path.join(root, 'mcp-server', 'index.js')],
    outfile: path.join(mcpDir, 'portpilot-mcp.mjs'),
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node18',
    legalComments: 'none',
    logLevel: 'warning',
    // CJS dependencies inside an ESM bundle still call require() for builtins.
    // Set on globalThis: a top-level `const require` would collide with the one
    // index.js declares for loadCore().
    banner: { js: "import { createRequire as __ppCreateRequire } from 'module'; globalThis.require ??= __ppCreateRequire(import.meta.url);" },
  });
  // LF always: a Windows checkout (core.autocrlf) has CRLF sources, and the
  // committed copies must match a build on either OS byte for byte.
  for (const name of ['configFile', 'status', 'runHistory']) {
    const src = fs.readFileSync(path.join(root, 'src', 'core', `${name}.js`), 'utf8');
    fs.writeFileSync(path.join(mcpDir, `${name}.cjs`), src.replace(/\r\n/g, '\n'));
  }

  await build({
    absWorkingDir: root,
    stdin: {
      contents: [
        "export { describeConflict, fmtAge, CONFIRM_MS } from './conflict.js';",
        "export { provenanceOf, statusOf, runtimeStateOf, CLAUDE_GLYPH } from './status.js';",
      ].join('\n'),
      resolveDir: path.join(root, 'src', 'core'),
      sourcefile: 'plugin-core-entry.js',
    },
    outfile: path.join(base, 'hooks', 'lib', 'core.mjs'),
    bundle: true,
    platform: 'neutral',
    format: 'esm',
    target: 'es2022',
    legalComments: 'none',
    logLevel: 'warning',
    banner: { js: '// Generated by scripts/build-plugin.mjs from src/core/conflict.js and status.js. Do not edit.' },
  });

  return OUTPUTS.flatMap((rel) => fs.readdirSync(path.join(base, rel))
    .filter((f) => /\.(c|m)js$/.test(f))
    .map((f) => `${rel}/${f}`)).sort();
}

if (!check) {
  const files = await buildTo(pluginDir);
  console.log(`plugin: ${files.join(', ')}`);
  process.exit(0);
}

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'pp-plugin-'));
try {
  const files = await buildTo(tmp);
  const stale = files.filter((f) => {
    const committed = path.join(pluginDir, f);
    return !fs.existsSync(committed)
      || !fs.readFileSync(committed).equals(fs.readFileSync(path.join(tmp, f)));
  });
  if (stale.length) {
    console.error(`plugin build output is stale (${stale.join(', ')}). Run: npm run build:plugin`);
    process.exit(1);
  }
  console.log('plugin build output is up to date');
} finally {
  fs.rmSync(tmp, { recursive: true, force: true });
}
