// Generated by scripts/build-plugin.mjs from src/core/browserApi.js and its requires. Do not edit.
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  try {
    return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
  } catch (e) {
    throw mod = 0, e;
  }
};

// src/core/configFile.js
var require_configFile = __commonJS({
  "src/core/configFile.js"(exports2, module2) {
    var fs = require("fs");
    var path2 = require("path");
    var STALE_MS = 1e4;
    var LOCK_TIMEOUT_MS = 5e3;
    var RENAME_RETRY_MS = 1e3;
    var sleeper = new Int32Array(new SharedArrayBuffer(4));
    function sleepSync(ms) {
      Atomics.wait(sleeper, 0, 0, ms);
    }
    function readJson(file, fallback) {
      try {
        return JSON.parse(fs.readFileSync(file, "utf8"));
      } catch (err) {
        if (err.code !== "ENOENT") {
          console.error(`[configFile] Failed to read ${file}:`, err.message);
          if (err instanceof SyntaxError) {
            try {
              fs.copyFileSync(file, `${file}.corrupt-${Date.now()}`);
            } catch {
            }
          }
        }
        return typeof fallback === "function" ? fallback() : fallback;
      }
    }
    function writeJsonAtomic(file, data) {
      fs.mkdirSync(path2.dirname(file), { recursive: true });
      const tmp = `${file}.${process.pid}.${Math.random().toString(36).slice(2, 10)}.tmp`;
      const fd = fs.openSync(tmp, "w");
      try {
        fs.writeSync(fd, JSON.stringify(data, null, 2));
        fs.fsyncSync(fd);
      } finally {
        fs.closeSync(fd);
      }
      const deadline = Date.now() + RENAME_RETRY_MS;
      for (; ; ) {
        try {
          fs.renameSync(tmp, file);
          return;
        } catch (err) {
          const transient = ["EPERM", "EBUSY", "EACCES"].includes(err.code);
          if (!transient || Date.now() > deadline) {
            try {
              fs.unlinkSync(tmp);
            } catch {
            }
            throw err;
          }
          sleepSync(10);
        }
      }
    }
    function readLockToken(lockPath) {
      try {
        return fs.readFileSync(lockPath, "utf8");
      } catch {
        return null;
      }
    }
    function breakStaleLock(lockPath, staleToken) {
      const aside = `${lockPath}.stale-${process.pid}-${Math.random().toString(36).slice(2, 10)}`;
      try {
        fs.renameSync(lockPath, aside);
      } catch {
        return;
      }
      let live = true;
      try {
        live = readLockToken(aside) !== staleToken || Date.now() - fs.statSync(aside).mtimeMs <= STALE_MS;
      } catch {
      }
      if (live) {
        try {
          fs.linkSync(aside, lockPath);
        } catch {
        }
      }
      try {
        fs.unlinkSync(aside);
      } catch {
      }
    }
    function withLock(file, fn) {
      const lockPath = `${file}.lock`;
      const token = `${process.pid}-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
      fs.mkdirSync(path2.dirname(file), { recursive: true });
      const deadline = Date.now() + LOCK_TIMEOUT_MS;
      let fd;
      for (; ; ) {
        try {
          fd = fs.openSync(lockPath, "wx");
          break;
        } catch (err) {
          if (!["EEXIST", "EPERM", "EACCES"].includes(err.code)) throw err;
          if (err.code === "EEXIST") {
            let stale = false;
            try {
              stale = Date.now() - fs.statSync(lockPath).mtimeMs > STALE_MS;
            } catch {
            }
            if (stale) {
              const staleToken = readLockToken(lockPath);
              if (staleToken !== null) breakStaleLock(lockPath, staleToken);
              continue;
            }
          }
          if (Date.now() > deadline) throw new Error(`Timed out waiting for config lock ${lockPath} (${err.code})`);
          sleepSync(5 + Math.floor(Math.random() * 20));
        }
      }
      try {
        fs.writeSync(fd, token);
        fs.closeSync(fd);
        return fn();
      } finally {
        if (readLockToken(lockPath) === token) {
          try {
            fs.unlinkSync(lockPath);
          } catch {
          }
        }
      }
    }
    function updateJson(file, mutator, fallback) {
      return withLock(file, () => {
        const config = readJson(file, fallback);
        const before = JSON.stringify(config);
        const result = mutator(config);
        if (JSON.stringify(config) !== before || !fs.existsSync(file)) writeJsonAtomic(file, config);
        return { config, result };
      });
    }
    function runtimePathFor(configPath) {
      return path2.join(path2.dirname(configPath), "portpilot-runtime.json");
    }
    var emptyRuntime = () => ({ apps: {} });
    function history(call2) {
      try {
        let mod = null;
        for (const p of ["./runHistory", "./runHistory.cjs"]) {
          try {
            mod = require(p);
            break;
          } catch (err) {
            if (err.code !== "MODULE_NOT_FOUND") throw err;
          }
        }
        if (mod) call2(mod);
      } catch (err) {
        console.error("[configFile] Run history failed:", err.message);
      }
    }
    function readRuntime(configPath) {
      const runtime = readJson(runtimePathFor(configPath), emptyRuntime);
      if (!runtime.apps || typeof runtime.apps !== "object") runtime.apps = {};
      return runtime;
    }
    function recordStart(configPath, appId, startedBy, { pid = null, port = null, rerunOf = null } = {}) {
      if (!appId || !startedBy) return false;
      let stamped = false;
      try {
        updateJson(runtimePathFor(configPath), (runtime) => {
          if (!runtime.apps || typeof runtime.apps !== "object") runtime.apps = {};
          runtime.apps[appId] = { startedBy, pid: pid || null, port: port || null };
        }, emptyRuntime);
        stamped = true;
      } catch (err) {
        console.error("[configFile] Failed to record app start:", err.message);
      }
      history((h) => h.openRun(configPath, appId, startedBy, { port, rerunOf }));
      return stamped;
    }
    function recordStop(configPath, appId) {
      if (!appId) return false;
      history((h) => h.closeRun(configPath, appId, { endedBy: "stop" }));
      try {
        updateJson(runtimePathFor(configPath), (runtime) => {
          if (runtime.apps && runtime.apps[appId]) delete runtime.apps[appId];
        }, emptyRuntime);
        return true;
      } catch (err) {
        console.error("[configFile] Failed to record app stop:", err.message);
        return false;
      }
    }
    var CRASH_TAIL_CHARS = 2e3;
    function recordCrash(configPath, appId, exitCode, { errorTail = null, port = null } = {}) {
      if (!appId) return false;
      history((h) => h.closeRun(configPath, appId, { endedBy: "crash", exitCode }));
      try {
        updateJson(runtimePathFor(configPath), (runtime) => {
          if (!runtime.apps || typeof runtime.apps !== "object") runtime.apps = {};
          const prev = runtime.apps[appId] || {};
          runtime.apps[appId] = {
            crashed: {
              exitCode: exitCode ?? null,
              at: Date.now(),
              startedBy: prev.startedBy || prev.crashed && prev.crashed.startedBy || null,
              port: port || prev.port || null,
              errorTail: errorTail ? String(errorTail).slice(-CRASH_TAIL_CHARS) : null
            }
          };
        }, emptyRuntime);
        return true;
      } catch (err) {
        console.error("[configFile] Failed to record app crash:", err.message);
        return false;
      }
    }
    function logPathFor(configPath, appId) {
      const safe = String(appId).replace(/[^A-Za-z0-9_-]/g, "_").slice(0, 120);
      return path2.join(path2.dirname(configPath), "logs", `${safe}.log`);
    }
    function readLogTail(configPath, appId, chars = CRASH_TAIL_CHARS) {
      try {
        const file = logPathFor(configPath, appId);
        const { size } = fs.statSync(file);
        const fd = fs.openSync(file, "r");
        try {
          const len = Math.min(size, chars * 4);
          const buf = Buffer.alloc(len);
          fs.readSync(fd, buf, 0, len, size - len);
          return buf.toString("utf8").slice(-chars);
        } finally {
          fs.closeSync(fd);
        }
      } catch {
        return null;
      }
    }
    var SESSION_LIVE_MS = 45e3;
    var INBOX_KEEP = 20;
    var safeName = (id) => String(id).replace(/[^A-Za-z0-9_-]/g, "_").slice(0, 120);
    function sessionsDirFor(configPath) {
      return path2.join(path2.dirname(configPath), "sessions");
    }
    function inboxPathFor(configPath, sessionId) {
      return path2.join(path2.dirname(configPath), "inbox", `${safeName(sessionId)}.json`);
    }
    function liveSessions(configPath, now = Date.now()) {
      const dir = sessionsDirFor(configPath);
      let names;
      try {
        names = fs.readdirSync(dir);
      } catch {
        return [];
      }
      const out = [];
      for (const name of names) {
        if (!name.endsWith(".json")) continue;
        let beat = null;
        try {
          beat = JSON.parse(fs.readFileSync(path2.join(dir, name), "utf8"));
        } catch {
          continue;
        }
        if (!beat || typeof beat.sessionId !== "string" || !Number.isFinite(beat.at)) continue;
        if (now - beat.at >= SESSION_LIVE_MS || beat.at - now > SESSION_LIVE_MS) continue;
        out.push({ sessionId: beat.sessionId, cwd: typeof beat.cwd === "string" ? beat.cwd : null, at: beat.at });
      }
      return out.sort((a, b) => b.at - a.at);
    }
    function sendToSession(configPath, sessionId, appId, now = Date.now()) {
      if (!sessionId || !appId) return null;
      const request = { appId: String(appId), at: now };
      try {
        updateJson(inboxPathFor(configPath, sessionId), (inbox) => {
          const list = Array.isArray(inbox.requests) ? inbox.requests : [];
          const last = list.length ? Number(list[list.length - 1].at) || 0 : 0;
          if (request.at <= last) request.at = last + 1;
          inbox.requests = [...list, request].slice(-INBOX_KEEP);
        }, () => ({ requests: [] }));
        return request;
      } catch (err) {
        console.error("[configFile] Failed to write session inbox:", err.message);
        return null;
      }
    }
    module2.exports = {
      readJson,
      writeJsonAtomic,
      withLock,
      updateJson,
      runtimePathFor,
      readRuntime,
      recordStart,
      recordStop,
      recordCrash,
      logPathFor,
      readLogTail,
      CRASH_TAIL_CHARS,
      sessionsDirFor,
      inboxPathFor,
      liveSessions,
      sendToSession,
      SESSION_LIVE_MS
    };
  }
});

// src/core/browserDetect.js
var require_browserDetect = __commonJS({
  "src/core/browserDetect.js"(exports2, module2) {
    var fs = require("fs");
    var os = require("os");
    var path2 = require("path");
    var BROWSERS = [
      { id: "chrome", label: "Google Chrome" },
      { id: "edge", label: "Microsoft Edge" },
      { id: "brave", label: "Brave" },
      { id: "chromium", label: "Chromium" },
      { id: "opera", label: "Opera" },
      { id: "vivaldi", label: "Vivaldi" }
    ];
    var BROWSER_IDS = BROWSERS.map((b) => b.id);
    var WIN = {
      chrome: ["Google\\Chrome\\Application\\chrome.exe"],
      edge: ["Microsoft\\Edge\\Application\\msedge.exe"],
      brave: ["BraveSoftware\\Brave-Browser\\Application\\brave.exe"],
      chromium: ["Chromium\\Application\\chrome.exe"],
      opera: ["Opera\\opera.exe", "Programs\\Opera\\opera.exe"],
      vivaldi: ["Vivaldi\\Application\\vivaldi.exe"]
    };
    var MAC = {
      chrome: ["Google Chrome.app/Contents/MacOS/Google Chrome"],
      edge: ["Microsoft Edge.app/Contents/MacOS/Microsoft Edge"],
      brave: ["Brave Browser.app/Contents/MacOS/Brave Browser"],
      chromium: ["Chromium.app/Contents/MacOS/Chromium"],
      opera: ["Opera.app/Contents/MacOS/Opera"],
      vivaldi: ["Vivaldi.app/Contents/MacOS/Vivaldi"]
    };
    var LINUX = {
      chrome: ["google-chrome", "google-chrome-stable"],
      edge: ["microsoft-edge", "microsoft-edge-stable"],
      brave: ["brave-browser", "brave", "brave-browser-stable"],
      chromium: ["chromium", "chromium-browser"],
      opera: ["opera"],
      vivaldi: ["vivaldi", "vivaldi-stable"]
    };
    var LINUX_DIRS = [
      "/usr/bin",
      "/usr/local/bin",
      "/snap/bin",
      "/opt/google/chrome",
      "/opt/brave.com/brave",
      "/opt/microsoft/msedge",
      "/opt/vivaldi",
      "/opt/opera"
    ];
    function isFile(p) {
      try {
        return fs.statSync(p).isFile();
      } catch {
        return false;
      }
    }
    function candidatesFor(id, platform, env, home) {
      if (platform === "win32") {
        const roots = [env.ProgramFiles, env["ProgramFiles(x86)"], env.LOCALAPPDATA].filter(Boolean);
        return roots.flatMap((r) => WIN[id].map((rel) => path2.win32.join(r, rel)));
      }
      if (platform === "darwin") {
        return ["/Applications", path2.posix.join(home, "Applications")].flatMap((r) => MAC[id].map((rel) => path2.posix.join(r, rel)));
      }
      const dirs = [...String(env.PATH || "").split(":").filter(Boolean), ...LINUX_DIRS];
      return dirs.flatMap((d) => LINUX[id].map((n) => path2.posix.join(d, n)));
    }
    function detectBrowsers(o = {}) {
      const platform = o.platform || process.platform;
      const env = o.env || process.env;
      const home = o.home || os.homedir();
      const exists = o.exists || isFile;
      const found = [];
      for (const b of BROWSERS) {
        const hit = candidatesFor(b.id, platform, env, home).find((p) => exists(p));
        if (hit) found.push({ id: b.id, label: b.label, path: hit });
      }
      return found;
    }
    function browserIdFromPath(exePath) {
      const base = String(exePath || "").toLowerCase();
      if (base.includes("brave")) return "brave";
      if (base.includes("msedge") || base.includes("microsoft edge") || base.includes("microsoft-edge")) return "edge";
      if (base.includes("vivaldi")) return "vivaldi";
      if (base.includes("opera")) return "opera";
      if (base.includes("chrome") && !base.includes("chromium")) return "chrome";
      return "chromium";
    }
    module2.exports = { BROWSERS, BROWSER_IDS, detectBrowsers, browserIdFromPath };
  }
});

// src/core/browserProfiles.js
var require_browserProfiles = __commonJS({
  "src/core/browserProfiles.js"(exports2, module2) {
    var fs = require("fs");
    var os = require("os");
    var path2 = require("path");
    var configFile2 = require_configFile();
    var { BROWSER_IDS, browserIdFromPath } = require_browserDetect();
    var MODES = ["headed", "offscreen", "headless"];
    var PORT_MIN = 1024;
    var PORT_MAX = 65535;
    var NAME_RE = /^[A-Za-z0-9](?:[A-Za-z0-9._-]{0,62}[A-Za-z0-9_-])?$/;
    var RESERVED_RE = /^(con|prn|aux|nul|com[1-9]|lpt[1-9])$/i;
    var ProfileError = class extends Error {
      constructor(code, message) {
        super(message);
        this.name = "ProfileError";
        this.code = code;
      }
    };
    var emptyConfig = () => ({ apps: [], settings: {}, groups: [], browserProfiles: [] });
    var lower2 = (s) => String(s).toLowerCase();
    var goodName = (name) => NAME_RE.test(name) && !RESERVED_RE.test(name.split(".")[0]);
    var samePath = (p) => path2.resolve(p).replace(/[\\/]+$/, "").toLowerCase();
    var profilesRootFor = (configPath) => path2.join(path2.dirname(configPath), "browser-profiles");
    function userDataDirFor(configPath, profile) {
      const root = profilesRootFor(configPath);
      if (profile.userDataDir) {
        const dir2 = path2.resolve(String(profile.userDataDir));
        const banned = [path2.parse(dir2).root, os.homedir(), path2.dirname(configPath), root].map(samePath);
        if (!path2.isAbsolute(String(profile.userDataDir)) || banned.includes(samePath(dir2))) {
          throw new ProfileError("BAD_DIR", `userDataDir "${profile.userDataDir}" is not a safe profile folder`);
        }
        return dir2;
      }
      const name = String(profile.name);
      const dir = path2.join(root, name);
      if (!goodName(name) || path2.dirname(dir) !== root) {
        throw new ProfileError("BAD_NAME", `profile name "${name}" cannot be used as a folder name`);
      }
      return dir;
    }
    function assertDistinctDirs(configPath, profile, others) {
      const mine = samePath(userDataDirFor(configPath, profile));
      const clash = others.find((o) => samePath(userDataDirFor(configPath, o)) === mine);
      if (clash) throw new ProfileError("DUPLICATE_DIR", `profile "${clash.name}" already uses the folder ${mine}`);
    }
    function validateProfile(fields, others = []) {
      const f = fields || {};
      const name = typeof f.name === "string" ? f.name.trim() : "";
      if (!goodName(name)) {
        throw new ProfileError("BAD_NAME", "name must be 1-64 characters: letters, digits, dot, dash, underscore; starting with a letter or digit, not ending in a dot, not a Windows device name");
      }
      const port = Number(f.port);
      if (!Number.isInteger(port) || port < PORT_MIN || port > PORT_MAX) {
        throw new ProfileError("BAD_PORT", `port must be an integer from ${PORT_MIN} to ${PORT_MAX}`);
      }
      const browser = f.browser == null ? "chrome" : lower2(f.browser);
      if (!BROWSER_IDS.includes(browser)) {
        throw new ProfileError("BAD_BROWSER", `browser must be one of: ${BROWSER_IDS.join(", ")}`);
      }
      const mode = f.mode == null ? "headed" : lower2(f.mode);
      if (!MODES.includes(mode)) throw new ProfileError("BAD_MODE", `mode must be one of: ${MODES.join(", ")}`);
      const url = f.url == null ? "" : String(f.url).trim();
      if (url && !/^(https?|file):\/\//i.test(url) && url !== "about:blank") {
        throw new ProfileError("BAD_URL", "url must start with http://, https://, file:// or be about:blank");
      }
      const note = f.note == null ? "" : String(f.note).slice(0, 500);
      const clash = others.find((p) => lower2(p.name) === lower2(name));
      if (clash) throw new ProfileError("DUPLICATE_NAME", `a profile named "${clash.name}" already exists`);
      const portClash = others.find((p) => p.port === port);
      if (portClash) throw new ProfileError("DUPLICATE_PORT", `port ${port} is already used by profile "${portClash.name}"`);
      const out = { name, port, browser, mode, url, note };
      if (f.userDataDir != null && f.userDataDir !== "") {
        if (typeof f.userDataDir !== "string" || !path2.isAbsolute(f.userDataDir)) {
          throw new ProfileError("BAD_DIR", "userDataDir must be an absolute path");
        }
        out.userDataDir = f.userDataDir;
      }
      return out;
    }
    function listProfiles(configPath) {
      const config = configFile2.readJson(configPath, emptyConfig);
      return Array.isArray(config.browserProfiles) ? config.browserProfiles : [];
    }
    function getProfile(configPath, name) {
      const p = listProfiles(configPath).find((x) => lower2(x.name) === lower2(name || ""));
      if (!p) throw new ProfileError("NOT_FOUND", `no browser profile named "${name}"`);
      const clean = validateProfile(p, []);
      userDataDirFor(configPath, clean);
      return clean;
    }
    function mutateProfiles(configPath, fn) {
      return configFile2.updateJson(configPath, (config) => {
        if (!Array.isArray(config.browserProfiles)) config.browserProfiles = [];
        return fn(config.browserProfiles);
      }, emptyConfig).result;
    }
    function addProfile(configPath, fields) {
      return mutateProfiles(configPath, (list) => {
        const p = validateProfile(fields, list);
        assertDistinctDirs(configPath, p, list);
        list.push(p);
        return p;
      });
    }
    function updateProfile(configPath, name, changes) {
      return mutateProfiles(configPath, (list) => {
        const i = list.findIndex((x) => lower2(x.name) === lower2(name || ""));
        if (i === -1) throw new ProfileError("NOT_FOUND", `no browser profile named "${name}"`);
        const others = list.filter((_, j) => j !== i);
        const merged = validateProfile({ ...list[i], ...changes, name: list[i].name }, others);
        assertDistinctDirs(configPath, merged, others);
        list[i] = merged;
        return merged;
      });
    }
    function removeProfile(configPath, name, { purge = false } = {}) {
      let purged = false;
      if (purge) {
        const p = getProfile(configPath, name);
        if (!p.userDataDir) {
          fs.rmSync(userDataDirFor(configPath, p), { recursive: true, force: true });
          purged = true;
        }
      }
      const removed = mutateProfiles(configPath, (list) => {
        const i = list.findIndex((x) => lower2(x.name) === lower2(name || ""));
        if (i === -1) throw new ProfileError("NOT_FOUND", `no browser profile named "${name}"`);
        return list.splice(i, 1)[0];
      });
      return { removed, purged };
    }
    function importPool(configPath, poolPath, { adoptDirs = false } = {}) {
      let pool;
      try {
        pool = JSON.parse(fs.readFileSync(poolPath, "utf8"));
      } catch (err) {
        throw new ProfileError("BAD_POOL", `cannot read ${poolPath}: ${err.message}`);
      }
      if (!pool || !Array.isArray(pool.profiles)) throw new ProfileError("BAD_POOL", `${poolPath} has no "profiles" array`);
      const browser = browserIdFromPath(pool.bravePath || "brave");
      const imported = [];
      const skipped = [];
      mutateProfiles(configPath, (list) => {
        for (const entry of pool.profiles) {
          const e = entry || {};
          const fields = { name: e.name, port: e.port, mode: e.mode, url: e.url, note: e.description, browser };
          if (adoptDirs && pool.profileRoot && typeof e.name === "string") {
            const dir = path2.resolve(path2.dirname(poolPath), pool.profileRoot, e.name);
            if (fs.existsSync(dir)) fields.userDataDir = dir;
          }
          try {
            const p = validateProfile(fields, list);
            assertDistinctDirs(configPath, p, list);
            list.push(p);
            imported.push(p);
          } catch (err) {
            if (!(err instanceof ProfileError)) throw err;
            skipped.push({ name: String(e.name), reason: err.message });
          }
        }
      });
      return { imported, skipped };
    }
    module2.exports = {
      MODES,
      PORT_MIN,
      PORT_MAX,
      ProfileError,
      profilesRootFor,
      userDataDirFor,
      assertDistinctDirs,
      validateProfile,
      listProfiles,
      getProfile,
      addProfile,
      updateProfile,
      removeProfile,
      importPool
    };
  }
});

// src/core/browserCdp.js
var require_browserCdp = __commonJS({
  "src/core/browserCdp.js"(exports2, module2) {
    var PROBE_MS = 1500;
    var CALL_MS = 8e3;
    async function getJson(port, route) {
      try {
        const r = await fetch(`http://127.0.0.1:${port}${route}`, { signal: AbortSignal.timeout(PROBE_MS) });
        return r.ok ? await r.json() : null;
      } catch {
        return null;
      }
    }
    var version = (port) => getJson(port, "/json/version");
    async function pageTabs(port) {
      const list = await getJson(port, "/json");
      return (Array.isArray(list) ? list : []).filter((t) => t.type === "page").map((t) => ({ id: t.id, title: t.title || "", url: t.url || "" }));
    }
    async function withBrowserSession(port, fn) {
      if (typeof WebSocket !== "function") return null;
      const v = await version(port);
      if (!v || !v.webSocketDebuggerUrl) return null;
      const ws = new WebSocket(v.webSocketDebuggerUrl);
      let id = 0;
      const pending = /* @__PURE__ */ new Map();
      await new Promise((resolve, reject) => {
        ws.addEventListener("open", resolve, { once: true });
        ws.addEventListener("error", () => reject(new Error("CDP socket error")), { once: true });
      });
      ws.addEventListener("message", (ev) => {
        const msg = JSON.parse(ev.data);
        const p = pending.get(msg.id);
        if (!p) return;
        pending.delete(msg.id);
        if (msg.error) p.reject(new Error(msg.error.message));
        else p.resolve(msg.result);
      });
      const send = (method, params = {}) => new Promise((resolve, reject) => {
        const mid = ++id;
        pending.set(mid, { resolve, reject });
        ws.send(JSON.stringify({ id: mid, method, params }));
        setTimeout(() => {
          if (pending.delete(mid)) reject(new Error(`${method} timed out`));
        }, CALL_MS);
      });
      try {
        return await fn(send);
      } finally {
        try {
          ws.close();
        } catch {
        }
      }
    }
    async function closeBrowser(port) {
      try {
        const r = await withBrowserSession(port, (send) => send("Browser.close"));
        return r !== null;
      } catch {
        return false;
      }
    }
    async function parkOffscreen(port, left) {
      try {
        const out = await withBrowserSession(port, async (send) => {
          const [tab] = await pageTabs(port);
          if (!tab) return null;
          const { windowId } = await send("Browser.getWindowForTarget", { targetId: tab.id });
          await send("Browser.setWindowBounds", {
            windowId,
            bounds: { left, top: 0, width: 1440, height: 900, windowState: "normal" }
          });
          const { bounds } = await send("Browser.getWindowBounds", { windowId });
          return bounds.left;
        });
        if (out == null) return { parked: false, left: null };
        return { parked: Math.abs(out - left) < 100, left: out };
      } catch {
        return { parked: false, left: null };
      }
    }
    module2.exports = { version, pageTabs, withBrowserSession, closeBrowser, parkOffscreen };
  }
});

// src/core/status.js
var require_status = __commonJS({
  "src/core/status.js"(exports2, module2) {
    (function(root, factory) {
      const api = factory();
      if (typeof module2 !== "undefined" && module2.exports) module2.exports = api;
      if (typeof window !== "undefined") window.PortPilotStatus = api;
    })(typeof self !== "undefined" ? self : exports2, function() {
      "use strict";
      const STATES = {
        running: { state: "running", token: "--status-running", shape: "disc", glyph: "\u25CF", ascii: "*", label: "Running" },
        stopped: { state: "stopped", token: "--status-stopped", shape: "ring", glyph: "\u25CB", ascii: "o", label: "Stopped" },
        starting: { state: "starting", token: "--status-starting", shape: "disc-pulse", glyph: "\u25D0", ascii: "~", label: "Starting" },
        conflict: { state: "conflict", token: "--status-conflict", shape: "triangle", glyph: "\u25B2", ascii: "!", label: "Conflict" },
        error: { state: "error", token: "--status-error", shape: "circle-x", glyph: "\u2297", ascii: "x", label: "Error" },
        crashed: { state: "crashed", token: "--status-crashed", shape: "cross", glyph: "\u2715", ascii: "X", label: "Crashed" }
      };
      function statusOf(item) {
        const it = item || {};
        if (it.state && STATES[it.state]) return STATES[it.state];
        if (it.crashed) return STATES.crashed;
        if (it.error) return STATES.error;
        if (it.conflict) return STATES.conflict;
        if (it.starting) return STATES.starting;
        if (it.running) return STATES.running;
        return STATES.stopped;
      }
      const GROUPS = {
        dev: { key: "dev", label: "Dev Servers", order: 0, defaultCollapsed: false },
        other: { key: "other", label: "Other User Ports", order: 1, defaultCollapsed: false },
        system: { key: "system", label: "System & OS Ports", order: 2, defaultCollapsed: true }
      };
      const GROUP_ORDER = ["dev", "other", "system"];
      const SYSTEM_PROCESSES = /* @__PURE__ */ new Set([
        // Windows
        "system",
        "system idle process",
        "idle",
        "registry",
        "svchost.exe",
        "services.exe",
        "lsass.exe",
        "wininit.exe",
        "winlogon.exe",
        "smss.exe",
        "csrss.exe",
        "spoolsv.exe",
        "searchindexer.exe",
        "searchhost.exe",
        "dwm.exe",
        "taskhostw.exe",
        "vmms.exe",
        "vmwp.exe",
        "vmcompute.exe",
        "wslservice.exe",
        "msmpeng.exe",
        // macOS / Linux
        "launchd",
        "systemd",
        "systemd-resolve",
        "systemd-resolved",
        "rpcbind",
        "rpc.statd",
        "rpc.mountd",
        "mdnsresponder",
        "cupsd",
        "avahi-daemon",
        "dnsmasq",
        "smbd",
        "nmbd"
      ]);
      const SYSTEM_PORTS = /* @__PURE__ */ new Set([
        135,
        // MS RPC endpoint mapper
        137,
        138,
        139,
        // NetBIOS
        445,
        // SMB
        1900,
        // SSDP / UPnP
        2179,
        // Hyper-V VMConnect (vmms.exe)
        3702,
        // WS-Discovery
        5353,
        // mDNS / Bonjour
        5355,
        // LLMNR
        5357,
        // WSDAPI
        631
        // CUPS / IPP
      ]);
      const DEV_RUNTIME_TOKENS = [
        "node",
        "nodejs",
        "deno",
        "bun",
        "npm",
        "npx",
        "pnpm",
        "yarn",
        "nodemon",
        "vite",
        "next",
        "nuxt",
        "astro",
        "remix",
        "webpack",
        "rollup",
        "esbuild",
        "parcel",
        "turbo",
        "ng",
        "ember",
        "gatsby",
        "expo",
        "python",
        "python3",
        "uvicorn",
        "gunicorn",
        "hypercorn",
        "flask",
        "django",
        "fastapi",
        "streamlit",
        "php",
        "artisan",
        "ruby",
        "rails",
        "puma",
        "unicorn",
        "dotnet",
        "cargo",
        "hugo",
        "air"
      ];
      const DEV_RUNTIME_RE = new RegExp("\\b(" + DEV_RUNTIME_TOKENS.join("|") + ")\\b");
      const DEV_RANGE_MIN = 3e3;
      const DEV_RANGE_MAX = 9999;
      function classify(port, opts) {
        const p = port || {};
        const o = opts || {};
        const num = Number(p.port);
        const pid = p.pid;
        const proc = String(p.processName || "").toLowerCase().trim();
        const text = (proc + " " + String(p.commandLine || "")).toLowerCase();
        if (o.registered === true || p.appId != null || p.registered === true) return "dev";
        if (pid === 0 || pid === 4) return "system";
        if (SYSTEM_PROCESSES.has(proc)) return "system";
        if (SYSTEM_PORTS.has(num)) return "system";
        if (DEV_RUNTIME_RE.test(text) && num >= DEV_RANGE_MIN && num <= DEV_RANGE_MAX) return "dev";
        return "other";
      }
      const PROVENANCE_KINDS = ["human", "claude", "external"];
      const SURFACES = ["desktop", "web", "vscode", "claude-code", "mcp"];
      const CLAUDE_GLYPH = "\u2726";
      function makeStartedBy(fields) {
        const f = fields || {};
        if (!PROVENANCE_KINDS.includes(f.kind)) {
          throw new Error("startedBy.kind must be one of: " + PROVENANCE_KINDS.join(", "));
        }
        if (!SURFACES.includes(f.surface)) {
          throw new Error("startedBy.surface must be one of: " + SURFACES.join(", "));
        }
        const out = { kind: f.kind, surface: f.surface, at: f.at || (/* @__PURE__ */ new Date()).toISOString() };
        if (f.sessionId) out.sessionId = String(f.sessionId).slice(0, 200);
        if (f.label) out.label = String(f.label).slice(0, 100);
        return out;
      }
      function shortSession(id) {
        return id ? String(id).replace(/[^A-Za-z0-9]/g, "").slice(0, 4).toLowerCase() : "";
      }
      function provenanceOf(startedBy) {
        const s = startedBy || null;
        if (!s || s.kind === "external" || !PROVENANCE_KINDS.includes(s.kind)) {
          return { kind: "external", word: "external", glyph: "", title: "Found running - not started by PortPilot" };
        }
        const when = s.at ? ` at ${s.at}` : "";
        if (s.kind === "human") {
          return { kind: "human", word: "you", glyph: "", title: `Started by you from ${s.surface}${when}` };
        }
        const short = shortSession(s.sessionId);
        const session = s.sessionId ? ` (session ${s.sessionId}${s.label ? `, ${s.label}` : ""})` : "";
        return {
          kind: "claude",
          word: short ? `claude ${short}` : "claude",
          glyph: CLAUDE_GLYPH,
          title: `Started by Claude${session} via ${s.surface}${when}`
        };
      }
      const ROW_WORDS = { error: "Not responding", conflict: "Port blocked" };
      function formatUptime(sec) {
        const s = Number(sec);
        if (sec == null || !Number.isFinite(s) || s < 0) return "";
        if (s < 60) return `${Math.floor(s)}s`;
        if (s < 3600) return `${Math.floor(s / 60)}m`;
        if (s < 86400) return `${Math.floor(s / 3600)}h`;
        return `${Math.floor(s / 86400)}d`;
      }
      function rowStateOf(rec) {
        const r = rec || {};
        let key = "stopped";
        if (r.starting) key = "starting";
        else if (r.running) key = r.unhealthy ? "error" : "running";
        else if (r.conflict) key = "conflict";
        else if (r.crashed) key = "crashed";
        const s = STATES[key];
        const alive = key === "running" || key === "error";
        let reason = "";
        if (key === "crashed" && r.exitCode != null) reason = `exit ${r.exitCode}`;
        if (key === "conflict" && r.blockedBy) reason = String(r.blockedBy);
        const uptime = alive ? formatUptime(r.uptimeSec) : "";
        const prov = alive && r.startedBy ? provenanceOf(r.startedBy) : null;
        const provenance = prov && prov.kind !== "external" ? prov.word : "";
        const word = ROW_WORDS[key] || s.label;
        const head = `${s.glyph} ${word}${uptime ? " " + uptime : ""}`;
        const text = [head, reason, provenance].filter(Boolean).join(" \xB7 ");
        const title = [word + (reason ? ` (${reason})` : ""), uptime && `up ${uptime}`, prov && provenance && prov.title].filter(Boolean).join(" - ");
        return {
          state: key,
          shape: s.shape,
          glyph: s.glyph,
          ascii: s.ascii,
          token: s.token,
          word,
          reason,
          uptime,
          provenance,
          text,
          title
        };
      }
      const STARTING_GRACE_MS = 60 * 1e3;
      function runtimeStateOf(rt, opts) {
        const o = opts || {};
        if (o.listening) return "running";
        if (!rt) return null;
        if (rt.crashed) return "crashed";
        const at = rt.startedBy && Date.parse(rt.startedBy.at);
        const now = o.now == null ? Date.now() : o.now;
        if (Number.isFinite(at) && now - at < STARTING_GRACE_MS) return "starting";
        return "crashed";
      }
      return {
        STATES,
        statusOf,
        runtimeStateOf,
        STARTING_GRACE_MS,
        formatUptime,
        rowStateOf,
        PROVENANCE_KINDS,
        SURFACES,
        CLAUDE_GLYPH,
        makeStartedBy,
        shortSession,
        provenanceOf,
        GROUPS,
        GROUP_ORDER,
        classify,
        // Exposed for tests and future tuning.
        SYSTEM_PROCESSES,
        SYSTEM_PORTS,
        DEV_RUNTIME_RE,
        DEV_RANGE_MIN,
        DEV_RANGE_MAX
      };
    });
  }
});

// src/core/conflict.js
var require_conflict = __commonJS({
  "src/core/conflict.js"(exports2, module2) {
    (function(root, factory) {
      const api = factory(root);
      if (typeof module2 !== "undefined" && module2.exports) module2.exports = api;
      if (typeof window !== "undefined") window.PortPilotConflict = api;
    })(typeof self !== "undefined" ? self : exports2, function(root) {
      "use strict";
      const CONFIRM_MS = 3e3;
      function statusApi() {
        if (typeof module2 !== "undefined" && module2.exports) return require_status();
        return root && root.PortPilotStatus;
      }
      function fmtAge(seconds) {
        const s = Number(seconds);
        if (!Number.isFinite(s) || s < 0) return "";
        if (s < 60) return "just now";
        if (s < 3600) return `${Math.floor(s / 60)}m ago`;
        if (s < 86400) return `${Math.floor(s / 3600)}h ago`;
        return `${Math.floor(s / 86400)}d ago`;
      }
      function describeConflict(c) {
        const o = c || {};
        const port = Number(o.port);
        const holder = o.holder || {};
        const holderApp = o.holderApp && o.holderApp.name ? o.holderApp : null;
        const kind = holderApp ? "managed" : "unmanaged";
        const proc = holder.processName || "an unknown process";
        const holderName = holderApp ? holderApp.name : proc;
        const S = statusApi();
        const prov = o.holderStartedBy && S ? S.provenanceOf(o.holderStartedBy) : null;
        const known = prov && prov.kind !== "external";
        const details = [];
        if (holderApp) details.push(proc);
        if (holder.pid != null) details.push(`PID ${holder.pid}`);
        const age = fmtAge(holder.uptime);
        if (age) details.push(`started ${age}`);
        if (known) details.push(`started by ${prov.word}`);
        else if (!holderApp) details.push("not managed");
        const sentence = `:${port} is held by ${holderName}` + (details.length ? ` (${details.join(", ")})` : "");
        const title = known ? prov.title : "";
        const freePort = Number(o.freePort) || null;
        const appName = o.app && o.app.name ? o.app.name : "the app";
        const actions = [
          {
            id: "useFreePort",
            label: freePort ? `Use :${freePort} instead` : "Use next free port",
            title: `Start ${appName} on ${freePort ? `:${freePort}` : "the next free port"} for this run. The saved port stays :${port}.`,
            destructive: false,
            recommended: true
          },
          {
            id: "killAndStart",
            label: holderApp ? `Stop ${holderApp.name} & start` : "Kill & start",
            title: `End ${holderName}${holder.pid != null ? ` (PID ${holder.pid})` : ""}, then start ${appName} on :${port}`,
            confirmLabel: holderApp ? "Confirm stop?" : "Confirm kill?",
            destructive: true,
            recommended: false
          },
          {
            id: "showProcess",
            label: "Show process",
            title: `Find :${port} in the Ports list`,
            destructive: false,
            recommended: false
          }
        ];
        return { kind, port, holderName, sentence, title, actions };
      }
      function conflictKey(c) {
        const pid = c && c.occupiedBy ? c.occupiedBy.pid : null;
        return `${c && c.appId}:${c && c.port}:${pid == null ? "" : pid}`;
      }
      function conflictToast(seen, conflicts) {
        const list = Array.isArray(conflicts) ? conflicts : [];
        const keys = new Set(list.map(conflictKey));
        const fresh = list.filter((c) => !(seen && seen.has(conflictKey(c))));
        let message = null;
        if (fresh.length === 1) {
          const c = fresh[0];
          const h = c.occupiedBy || {};
          message = `Port ${c.port} blocked for ${c.appName} by ${h.processName || "Unknown"}` + (h.pid != null ? ` (PID ${h.pid})` : "");
        } else if (fresh.length > 1) {
          message = `${fresh.length} port conflicts - see the marked rows`;
        }
        return { keys, message };
      }
      return { CONFIRM_MS, fmtAge, describeConflict, conflictKey, conflictToast };
    });
  }
});

// src/core/browserRun.js
var require_browserRun = __commonJS({
  "src/core/browserRun.js"(exports2, module2) {
    var fs = require("fs");
    var path2 = require("path");
    var { execFile, spawn } = require("child_process");
    var cdp = require_browserCdp();
    var { detectBrowsers, BROWSERS } = require_browserDetect();
    var { getProfile, userDataDirFor, MODES } = require_browserProfiles();
    var { describeConflict } = require_conflict();
    var OFFSCREEN_LEFT = -2400;
    var START_TIMEOUT_MS = 1e4;
    var GRACE_MS = 6e3;
    var KILL_MS = 5e3;
    var RunError = class extends Error {
      constructor(code, message, extra = {}) {
        super(message);
        this.name = "RunError";
        this.code = code;
        Object.assign(this, extra);
      }
    };
    var sleep = (ms) => new Promise((r) => setTimeout(r, ms));
    var run2 = (file, args) => new Promise((resolve) => {
      execFile(
        file,
        args,
        { encoding: "utf8", timeout: 5e3, windowsHide: true, maxBuffer: 4 * 1024 * 1024 },
        (err, stdout) => resolve(err ? null : stdout)
      );
    });
    function parseNetstat(out, port) {
      for (const line of String(out || "").split(/\r?\n/)) {
        const m = line.match(/^\s*TCP\s+(\S+):(\d+)\s+(\S+):(\d+)\s+(?:\S+\s+)?(\d+)\s*$/i);
        if (m && Number(m[2]) === port && Number(m[4]) === 0 && /^(0\.0\.0\.0|\[::\]|\*)$/.test(m[3])) return Number(m[5]);
      }
      return null;
    }
    async function listenerPid(port) {
      if (process.platform === "win32") return parseNetstat(await run2("netstat", ["-ano"]), port);
      const lsof = await run2("lsof", ["-nP", `-iTCP:${port}`, "-sTCP:LISTEN", "-Fp"]);
      const p = (lsof || "").match(/^p(\d+)/m);
      if (p) return Number(p[1]);
      const ss = await run2("ss", ["-ltnpH", `sport = :${port}`]);
      const s = (ss || "").match(/pid=(\d+)/);
      return s ? Number(s[1]) : null;
    }
    async function describePid(pid) {
      if (process.platform === "win32") {
        const out = await run2("powershell.exe", [
          "-NoProfile",
          "-NonInteractive",
          "-Command",
          `Get-CimInstance Win32_Process -Filter "ProcessId=${Number(pid)}" | Select-Object Name,CommandLine | ConvertTo-Json -Compress`
        ]);
        try {
          const j = JSON.parse(out);
          return { processName: j.Name || null, commandLine: j.CommandLine || null };
        } catch {
          return { processName: null, commandLine: null };
        }
      }
      const args = await run2("ps", ["-ww", "-o", "args=", "-p", String(pid)]);
      const comm = await run2("ps", ["-o", "comm=", "-p", String(pid)]);
      return { processName: comm ? path2.basename(comm.trim()) : null, commandLine: args ? args.trim() : null };
    }
    async function inspectPort(port) {
      const pid = await listenerPid(port);
      if (pid == null) return null;
      return { pid, ...await describePid(pid) };
    }
    function killPid(pid) {
      if (process.platform === "win32") return run2("taskkill", ["/PID", String(pid), "/T", "/F"]);
      try {
        process.kill(pid, "SIGTERM");
      } catch {
      }
      return Promise.resolve();
    }
    var defaultDeps = () => ({
      spawn,
      inspectPort,
      kill: killPid,
      sleep,
      detect: () => detectBrowsers(),
      version: cdp.version,
      pageTabs: cdp.pageTabs,
      closeBrowser: cdp.closeBrowser,
      park: cdp.parkOffscreen
    });
    var norm = (s) => String(s).replace(/\\/g, "/").replace(/\/+$/, "").toLowerCase();
    var BROWSER_PROCESS_RE = /chrome|chromium|msedge|brave|opera|vivaldi|browser/i;
    function holdsDir(holder, dir) {
      if (!holder || !holder.commandLine) return false;
      if (holder.processName && !BROWSER_PROCESS_RE.test(holder.processName)) return false;
      const line = String(holder.commandLine).replace(/\\/g, "/");
      const want = norm(dir);
      const flag = /--user-data-dir=/gi;
      for (let m = flag.exec(line); m; m = flag.exec(line)) {
        const rest = line.slice(m.index + m[0].length).replace(/^"/, "").toLowerCase();
        if (!rest.startsWith(want)) continue;
        const tail = rest.slice(want.length);
        if (/^\/?"?(\s+(-|https?:|file:|about:)|\s*$)/.test(tail)) return true;
      }
      return false;
    }
    function reservationWarning(profile, holder) {
      const h = holder || {};
      const { sentence } = describeConflict({ port: profile.port, holder: h, app: { name: profile.name } });
      return {
        kind: "browser-port-held",
        profile: profile.name,
        port: profile.port,
        holder: { pid: h.pid ?? null, processName: h.processName || null },
        sentence: `${sentence}; browser profile "${profile.name}" reserves it`
      };
    }
    async function profileStatus(configPath, profile, d = defaultDeps()) {
      const dir = userDataDirFor(configPath, profile);
      const base = { name: profile.name, port: profile.port, browser: profile.browser, mode: profile.mode };
      const holder = await d.inspectPort(profile.port);
      const v = await d.version(profile.port);
      const up = async (owner) => ({
        ...base,
        state: "up",
        owner,
        pid: holder ? holder.pid : null,
        browserVersion: v ? v.Browser || null : null,
        tabs: v ? await d.pageTabs(profile.port) : []
      });
      if (holder && holdsDir(holder, dir)) return up("profile");
      if (holder && holder.commandLine) {
        return { ...base, state: "blocked", pid: holder.pid, tabs: [], warning: reservationWarning(profile, holder) };
      }
      if (v) return up("unverified");
      if (holder) return { ...base, state: "blocked", pid: holder.pid, tabs: [], warning: reservationWarning(profile, holder) };
      return { ...base, state: "down", pid: null, tabs: [] };
    }
    async function allStatus(configPath, profiles2, d = defaultDeps()) {
      const rows = [];
      for (const p of profiles2) rows.push(await profileStatus(configPath, p, d));
      return { rows, warnings: rows.filter((r) => r.warning).map((r) => r.warning) };
    }
    function buildArgs(profile, mode, dir, { offscreenLeft = OFFSCREEN_LEFT } = {}) {
      const args = [
        `--remote-debugging-port=${profile.port}`,
        `--user-data-dir=${dir}`,
        "--no-first-run",
        "--no-default-browser-check",
        "--hide-crash-restore-bubble"
      ];
      if (profile.browser === "brave") args.push("--disable-features=BraveRewards,BraveWallet");
      if (mode === "headless") args.push("--headless=new");
      if (mode === "offscreen") args.push(`--window-position=${offscreenLeft},0`);
      args.push("--", profile.url || "about:blank");
      return args;
    }
    function clearSessions(dir) {
      const sessions = path2.join(dir, "Default", "Sessions");
      let names = [];
      try {
        names = fs.readdirSync(sessions);
      } catch {
        return;
      }
      for (const f of names) {
        try {
          fs.rmSync(path2.join(sessions, f), { force: true });
        } catch {
        }
      }
    }
    async function startProfile(configPath, name, o = {}, d = defaultDeps()) {
      const profile = getProfile(configPath, name);
      const mode = o.mode || profile.mode;
      if (!MODES.includes(mode)) throw new RunError("BAD_MODE", `mode must be one of: ${MODES.join(", ")}`);
      const before = await profileStatus(configPath, profile, d);
      if (before.state === "up" && before.owner === "profile") return { ...before, already: true };
      if (before.state === "up") {
        throw new RunError("NOT_VERIFIED", `:${profile.port} answers CDP but its owner cannot be identified, so it is not treated as profile "${profile.name}". Close it or pick another port.`);
      }
      if (before.state === "blocked") {
        throw new RunError(
          "PORT_HELD",
          `${before.warning.sentence}. Not started; nothing was killed.`,
          { holder: before.warning.holder, warning: before.warning }
        );
      }
      const exe = d.detect().find((b) => b.id === profile.browser);
      if (!exe) {
        const label = (BROWSERS.find((b) => b.id === profile.browser) || {}).label || profile.browser;
        const have = d.detect().map((b) => b.id).join(", ") || "none";
        throw new RunError("BROWSER_NOT_FOUND", `${label} is not installed (installed: ${have}). Change the profile's browser.`);
      }
      const dir = userDataDirFor(configPath, profile);
      fs.mkdirSync(dir, { recursive: true });
      clearSessions(dir);
      let spawnError = null;
      const child = d.spawn(exe.path, buildArgs(profile, mode, dir), {
        detached: true,
        stdio: "ignore",
        windowsHide: mode === "headless"
      });
      if (child && child.on) child.on("error", (err) => {
        spawnError = err;
      });
      if (child && child.unref) child.unref();
      const timeoutMs = o.timeoutMs || START_TIMEOUT_MS;
      const pollMs = o.pollMs || 250;
      let v = null;
      for (let waited = 0; !v && !spawnError && waited < timeoutMs; waited += pollMs) {
        await d.sleep(pollMs);
        v = await d.version(profile.port);
      }
      if (spawnError) throw new RunError("LAUNCH_FAILED", `could not launch ${exe.path}: ${spawnError.message}`);
      if (!v) {
        if (child && child.pid) await d.kill(child.pid);
        throw new RunError("START_TIMEOUT", `${profile.name}: nothing answered CDP on :${profile.port} within ${timeoutMs} ms. If this user-data-dir is already open in another browser window, that window took the launch; close it and retry.`);
      }
      const after = await profileStatus(configPath, profile, d);
      if (after.state !== "up") {
        throw new RunError(
          "PORT_HELD",
          `${after.warning ? after.warning.sentence : `:${profile.port} is not held by this profile`}. The launch did not take the port.`,
          after.warning ? { holder: after.warning.holder, warning: after.warning } : {}
        );
      }
      const out = { ...after, already: false };
      if (mode === "offscreen") out.offscreen = await d.park(profile.port, OFFSCREEN_LEFT);
      return out;
    }
    async function waitDown(profile, d, ms, pollMs) {
      for (let waited = 0; waited < ms; waited += pollMs) {
        if (!await d.version(profile.port) && !await d.inspectPort(profile.port)) return true;
        await d.sleep(pollMs);
      }
      return false;
    }
    async function stopProfile(configPath, name, o = {}, d = defaultDeps()) {
      const profile = getProfile(configPath, name);
      const st = await profileStatus(configPath, profile, d);
      if (st.state === "down") return { ...st, already: true, stoppedBy: null };
      if (st.state === "blocked") {
        throw new RunError(
          "NOT_OURS",
          `${st.warning.sentence}. Not stopping a process this profile did not start.`,
          { holder: st.warning.holder, warning: st.warning }
        );
      }
      if (st.owner !== "profile") {
        throw new RunError("NOT_VERIFIED", `:${profile.port} answers CDP but its owner cannot be identified, so it is not stopped. Close it by hand.`);
      }
      const pollMs = o.pollMs || 250;
      await d.closeBrowser(profile.port);
      if (await waitDown(profile, d, o.graceMs ?? GRACE_MS, pollMs)) {
        return { ...await profileStatus(configPath, profile, d), already: false, stoppedBy: "cdp" };
      }
      const now = await d.inspectPort(profile.port);
      if (now && now.pid === st.pid && holdsDir(now, userDataDirFor(configPath, profile))) await d.kill(st.pid);
      if (await waitDown(profile, d, o.killMs ?? KILL_MS, pollMs)) {
        return { ...await profileStatus(configPath, profile, d), already: false, stoppedBy: "pid" };
      }
      throw new RunError("STOP_FAILED", `${profile.name} (PID ${st.pid}) is still up on :${profile.port}. Close it by hand.`);
    }
    module2.exports = {
      RunError,
      OFFSCREEN_LEFT,
      defaultDeps,
      inspectPort,
      parseNetstat,
      holdsDir,
      reservationWarning,
      profileStatus,
      allStatus,
      buildArgs,
      startProfile,
      stopProfile
    };
  }
});

// src/core/browserApi.js
var path = require("path");
var configFile = require_configFile();
var profiles = require_browserProfiles();
var run = require_browserRun();
var CLAIMS_FILE = "portpilot-browser-claims.json";
var emptyClaims = () => ({ profiles: {} });
var lower = (s) => String(s).toLowerCase();
var ApiError = class extends Error {
  constructor(code, message) {
    super(message);
    this.name = "ApiError";
    this.code = code;
  }
};
var claimsPathFor = (configPath) => path.join(path.dirname(configPath), CLAIMS_FILE);
function readClaims(configPath) {
  const file = configFile.readJson(claimsPathFor(configPath), emptyClaims);
  return file && file.profiles && typeof file.profiles === "object" ? file.profiles : {};
}
function writeClaim(configPath, name, claim) {
  try {
    configFile.updateJson(claimsPathFor(configPath), (file) => {
      if (!file.profiles || typeof file.profiles !== "object") file.profiles = {};
      if (claim) file.profiles[lower(name)] = claim;
      else delete file.profiles[lower(name)];
    }, emptyClaims);
  } catch (err) {
    console.error("[browserApi] Failed to write claim:", err.message);
  }
}
function liveClaim(configPath, st) {
  if (st.state !== "up") return null;
  const c = readClaims(configPath)[lower(st.name)];
  if (!c || typeof c.by !== "string") return null;
  if (c.pid != null && st.pid != null && c.pid !== st.pid) return null;
  return c;
}
var publicClaim = (c) => {
  const out = { by: c.by, surface: c.surface, at: c.at };
  if (c.sessionId) out.sessionId = c.sessionId;
  return out;
};
function callerOf(args, ctx) {
  const clean = (s) => String(s || "").replace(/[\u0000-\u001f\u007f]/g, " ").trim().slice(0, 100);
  const sessionId = clean(args.sessionId).slice(0, 200);
  const short = sessionId.replace(/[^A-Za-z0-9]/g, "").slice(0, 4).toLowerCase();
  const by = clean(args.agent) || (short ? `claude ${short}` : `unnamed ${ctx.surface} caller`);
  const out = { by, surface: ctx.surface, at: (/* @__PURE__ */ new Date()).toISOString() };
  if (sessionId) out.sessionId = sessionId;
  return out;
}
function ago(iso) {
  const s = Math.max(0, Math.round((Date.now() - Date.parse(iso)) / 1e3));
  if (!Number.isFinite(s)) return "earlier";
  if (s < 90) return `${s}s ago`;
  if (s < 5400) return `${Math.round(s / 60)}m ago`;
  return `${Math.round(s / 3600)}h ago`;
}
var cdpUrlFor = (port) => `http://127.0.0.1:${port}`;
function view(st, claim) {
  const out = { name: st.name, port: st.port, cdpUrl: cdpUrlFor(st.port), state: st.state, mode: st.mode, browser: st.browser };
  if (claim) out.claim = publicClaim(claim);
  if (st.warning) {
    out.warning = st.warning.sentence;
    out.holder = st.warning.holder;
  }
  return out;
}
var NEXT = {
  NOT_FOUND: "Call list_browser_profiles and use one of the names it returns.",
  BAD_ARGS: 'Send the profile name as "name".',
  PORT_HELD: "Do not kill it and do not pick another port. Tell the user which process holds the port and ask them to free it.",
  NOT_OURS: "Leave it running: this profile did not start that process. Ask the user.",
  NOT_VERIFIED: "Leave it alone and ask the user to close that browser by hand.",
  BROWSER_NOT_FOUND: "Call list_browsers, then ask the user to set the profile to an installed browser.",
  START_TIMEOUT: "Call start_browser once more. If it fails again, ask the user to close any window using this profile.",
  LAUNCH_FAILED: "Ask the user to check that the browser starts normally.",
  STOP_FAILED: "Ask the user to close that browser window by hand.",
  BAD_MODE: `Use one of: ${profiles.MODES.join(", ")}.`,
  UNKNOWN_TOOL: "Use one of: list_browser_profiles, list_browsers, start_browser, stop_browser, set_browser_mode."
};
function failure(err, configPath) {
  const code = typeof err.code === "string" && /^[A-Z_]+$/.test(err.code) ? err.code : "INTERNAL";
  const out = {
    success: false,
    code,
    error: String(err.message || err).replace(/\s+/g, " ").trim(),
    action: NEXT[code] || "Report this error to the user."
  };
  if (err.holder) out.holder = err.holder;
  if (code === "NOT_FOUND") {
    try {
      out.known = profiles.listProfiles(configPath).map((p) => p.name);
    } catch {
    }
  }
  return out;
}
var nameOf = (args) => {
  if (typeof args.name !== "string" || !args.name.trim()) {
    throw new ApiError("BAD_ARGS", "name is required: the profile name, as returned by list_browser_profiles");
  }
  return args.name.trim();
};
var runOpts = (ctx) => ctx.pollMs ? { pollMs: ctx.pollMs } : {};
var TOOLS = {
  async list_browser_profiles(configPath, args, ctx) {
    const stored = profiles.listProfiles(configPath);
    const { rows, warnings } = await run.allStatus(configPath, stored, ctx.deps);
    const out = rows.map((st) => {
      const row = view(st, liveClaim(configPath, st));
      const p = stored.find((x) => x.name === st.name) || {};
      if (p.url) row.url = p.url;
      if (p.note) row.note = p.note;
      if (st.tabs && st.tabs.length) row.tabs = st.tabs.slice(0, 5).map((t) => ({ title: t.title, url: t.url }));
      return row;
    });
    return { success: true, profiles: out, warnings: warnings.map((w) => w.sentence) };
  },
  async list_browsers(configPath, args, ctx) {
    return { success: true, browsers: ctx.deps.detect().map((b) => ({ id: b.id, label: b.label })) };
  },
  async start_browser(configPath, args, ctx) {
    const name = nameOf(args);
    profiles.getProfile(configPath, name);
    const caller = callerOf(args, ctx);
    const r = await run.startProfile(configPath, name, runOpts(ctx), ctx.deps);
    let claim = r.already ? liveClaim(configPath, r) : null;
    if (!claim) {
      claim = { ...caller, pid: r.pid ?? null };
      writeClaim(configPath, r.name, claim);
    }
    const out = { ...view(r, claim), already: !!r.already };
    if (r.offscreen) out.offscreen = r.offscreen;
    if (claim.by !== caller.by) {
      out.claimNote = `Claimed by "${claim.by}" (${ago(claim.at)}). Not blocked: you may use it, but leave tabs you did not open alone.`;
    }
    return { success: true, ...out };
  },
  async stop_browser(configPath, args, ctx) {
    const name = nameOf(args);
    const profile = profiles.getProfile(configPath, name);
    const caller = callerOf(args, ctx);
    const before = liveClaim(configPath, await run.profileStatus(configPath, profile, ctx.deps));
    const r = await run.stopProfile(configPath, name, runOpts(ctx), ctx.deps);
    writeClaim(configPath, profile.name, null);
    const out = { ...view(r, null), already: !!r.already };
    if (before && before.by !== caller.by) {
      out.claimNote = `Was claimed by "${before.by}" (${ago(before.at)}). Stopped anyway: claims are advisory.`;
    }
    return { success: true, ...out };
  },
  async set_browser_mode(configPath, args, ctx) {
    const name = nameOf(args);
    profiles.getProfile(configPath, name);
    const p = profiles.updateProfile(configPath, name, { mode: args.mode });
    const st = await run.profileStatus(configPath, p, ctx.deps);
    const out = { ...view(st, liveClaim(configPath, st)) };
    if (st.state === "up") {
      out.note = "The running browser keeps its old mode. Call stop_browser, then start_browser, to apply it.";
    }
    return { success: true, ...out };
  }
};
var TOOL_NAMES = Object.keys(TOOLS);
async function call(configPath, tool, args, ctx = {}) {
  try {
    if (!Object.prototype.hasOwnProperty.call(TOOLS, tool)) {
      throw new ApiError("UNKNOWN_TOOL", `there is no browser tool named "${tool}"`);
    }
    const full = { surface: "mcp", ...ctx, deps: ctx.deps || run.defaultDeps() };
    return await TOOLS[tool](configPath, args && typeof args === "object" ? args : {}, full);
  } catch (err) {
    return failure(err, configPath);
  }
}
module.exports = { TOOL_NAMES, call, claimsPathFor, cdpUrlFor };
